# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1.5951f,0f,1.5951f,0f,0f,2.3004f,0f,0f,-1.5951f,0f,-1.5951f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1.0634f,0f,-1.0634f,0f,0f,1.5336f,0f,3.834f,1.0634f,0f,-1.0634f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-4.5952f,0f,0f,0f,0f,4.686f,0f,0f,0f,0f,-4.5952f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.7253,"pz":0,"ry":0,"rx":0}}}