# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1.6168f,0f,1.6168f,0f,0f,2.2698f,0f,0f,-1.6168f,0f,-1.6168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1.0778f,0f,-1.0778f,0f,0f,1.5132f,0f,3.783f,1.0778f,0f,-1.0778f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-4.6576f,0f,0f,0f,0f,4.6237f,0f,0f,0f,0f,-4.6576f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.7023499999999998,"pz":0,"ry":0,"rx":0}}}