# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1.6266f,0f,1.6266f,0f,0f,2.2558f,0f,0f,-1.6266f,0f,-1.6266f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1.0844f,0f,-1.0844f,0f,0f,1.5039f,0f,3.7598f,1.0844f,0f,-1.0844f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-4.686f,0f,0f,0f,0f,4.5953f,0f,0f,0f,0f,-4.686f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.6918875,"pz":0,"ry":0,"rx":0}}}