# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1.605f,0f,1.605f,0f,0f,2.2865f,0f,0f,-1.605f,0f,-1.605f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1.07f,0f,-1.07f,0f,0f,1.5243f,0f,3.8108f,1.07f,0f,-1.07f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-4.6237f,0f,0f,0f,0f,4.6576f,0f,0f,0f,0f,-4.6237f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.7148375,"pz":0,"ry":0,"rx":0}}}