# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1.5996f,0f,1.5996f,0f,0f,2.2941f,0f,0f,-1.5996f,0f,-1.5996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1.0664f,0f,-1.0664f,0f,0f,1.5294f,0f,3.8235f,1.0664f,0f,-1.0664f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-4.6081f,0f,0f,0f,0f,4.6732f,0f,0f,0f,0f,-4.6081f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.7205749999999997,"pz":0,"ry":0,"rx":0}}}