# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:rocket/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'd4405388dfe29d515545b9bc138a2991e449fcda902be9f6e13a514532308f3d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack