# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:rocket/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'dc42c71cff679aed62985753fb2cfdd5012f649eb53cb57c51a18ffc3c423b70'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack