# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mcdevyt/animations/pause_all
tag @s add aj.mcdevyt.animation.floating.playing
scoreboard players set @s aj.floating.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:mcdevyt/animations/floating/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only