# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0975dfd28a01a654e948161dccdd8954ed09e27c2468da5d8344db5abe4d258f'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack