# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6abb5270bf8a69e5997ebd48e6db3742f88ad6bc10a9d8d3d9e1ef65d2621128'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack