# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:rocket/animations/rocket_idle/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.rocket_idle.frame 1