# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_thrust) {transformation: [-1f,0f,0f,0f,0f,1.025f,0f,0.0641f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window) {transformation: [-2.25f,0f,0f,0f,0f,2.3063f,0f,0f,0f,0f,-2.25f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window3) {transformation: [0f,0f,-2.25f,0f,0f,2.3063f,0f,0f,2.25f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window2) {transformation: [1f,0f,0f,0f,0f,1.025f,0f,2.9469f,0f,0f,1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window4) {transformation: [0f,0f,-2.25f,0f,0f,2.3063f,0f,0f,2.25f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-2.625f,0f,0f,0f,0f,2.6906f,0f,0f,0f,0f,-2.625f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.7296874999999998,"pz":0,"ry":0,"rx":0}}}