# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_thrust) {transformation: [-1.0014f,0f,0f,0f,0f,1.0243f,0f,0.064f,0f,0f,-1.0007f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window) {transformation: [-2.2532f,0f,0f,0f,0f,2.3047f,0f,0f,0f,0f,-2.2516f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window3) {transformation: [0f,0f,-2.2532f,0f,0f,2.3047f,0f,0f,2.2516f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window2) {transformation: [1.0014f,0f,0f,0f,0f,1.0243f,0f,2.9449f,0f,0f,1.0007f,-0.7505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window4) {transformation: [0f,0f,-2.2532f,0f,0f,2.3047f,0f,0f,2.2516f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-2.6287f,0f,0f,0f,0f,2.6888f,0f,0f,0f,0f,-2.6268f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.72850625,"pz":0,"ry":0,"rx":0}}}