# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_thrust) {transformation: [-1.025f,0f,0f,0f,0f,1.0125f,0f,0.0633f,0f,0f,-1.0125f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window) {transformation: [-2.3063f,0f,0f,0f,0f,2.2781f,0f,0f,0f,0f,-2.2781f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window3) {transformation: [0f,0f,-2.3063f,0f,0f,2.2781f,0f,0f,2.2781f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window2) {transformation: [1.025f,0f,0f,0f,0f,1.0125f,0f,2.9109f,0f,0f,1.0125f,-0.7594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window4) {transformation: [0f,0f,-2.3063f,0f,0f,2.2781f,0f,0f,2.2781f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-2.6906f,0f,0f,0f,0f,2.6578f,0f,0f,0f,0f,-2.6578f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.70859375,"pz":0,"ry":0,"rx":0}}}