# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_thrust) {transformation: [-1.0324f,0f,0f,0f,0f,1.0088f,0f,0.0631f,0f,0f,-1.0162f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window) {transformation: [-2.3229f,0f,0f,0f,0f,2.2698f,0f,0f,0f,0f,-2.2864f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window3) {transformation: [0f,0f,-2.3229f,0f,0f,2.2698f,0f,0f,2.2865f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window2) {transformation: [1.0324f,0f,0f,0f,0f,1.0088f,0f,2.9003f,0f,0f,1.0162f,-0.7621f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window4) {transformation: [0f,0f,-2.3229f,0f,0f,2.2698f,0f,0f,2.2865f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-2.7101f,0f,0f,0f,0f,2.6481f,0f,0f,0f,0f,-2.6675f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.7023499999999998,"pz":0,"ry":0,"rx":0}}}