# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_thrust) {transformation: [-1.0448f,0f,0f,0f,0f,1.0026f,0f,0.0627f,0f,0f,-1.0224f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window) {transformation: [-2.3508f,0f,0f,0f,0f,2.2558f,0f,0f,0f,0f,-2.3004f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window3) {transformation: [0f,0f,-2.3508f,0f,0f,2.2558f,0f,0f,2.3004f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window2) {transformation: [1.0448f,0f,0f,0f,0f,1.0026f,0f,2.8825f,0f,0f,1.0224f,-0.7668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window4) {transformation: [0f,0f,-2.3508f,0f,0f,2.2558f,0f,0f,2.3004f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-2.7426f,0f,0f,0f,0f,2.6318f,0f,0f,0f,0f,-2.6838f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.6918875,"pz":0,"ry":0,"rx":0}}}