# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_thrust) {transformation: [-1.0392f,0f,0f,0f,0f,1.0054f,0f,0.0628f,0f,0f,-1.0196f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window) {transformation: [-2.3382f,0f,0f,0f,0f,2.2622f,0f,0f,0f,0f,-2.2941f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window3) {transformation: [0f,0f,-2.3382f,0f,0f,2.2622f,0f,0f,2.2941f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window2) {transformation: [1.0392f,0f,0f,0f,0f,1.0054f,0f,2.8905f,0f,0f,1.0196f,-0.7647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_window4) {transformation: [0f,0f,-2.3382f,0f,0f,2.2622f,0f,0f,2.2941f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rocket) {transformation: [-2.7279f,0f,0f,0f,0f,2.6392f,0f,0f,0f,0f,-2.6764f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":1.6966125,"pz":0,"ry":0,"rx":0}}}