# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:mcdevyt rig_hash set value '6abb5270bf8a69e5997ebd48e6db3742f88ad6bc10a9d8d3d9e1ef65d2621128'
scoreboard objectives add aj.floating.frame dummy