# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:mcdevyt rig_hash set value '0975dfd28a01a654e948161dccdd8954ed09e27c2468da5d8344db5abe4d258f'
scoreboard objectives add aj.floating.frame dummy