# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:rocket rig_hash set value 'dc42c71cff679aed62985753fb2cfdd5012f649eb53cb57c51a18ffc3c423b70'
scoreboard objectives add aj.animation_rocket_idle.frame dummy