# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:rocket rig_hash set value 'd4405388dfe29d515545b9bc138a2991e449fcda902be9f6e13a514532308f3d'
scoreboard objectives add aj.rocket_idle.frame dummy