# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:rocket/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.rocket.node.foot] run data merge entity @s { transformation: [-1.591f,0f,1.591f,0f,0f,2.25f,0f,0f,-1.591f,0f,-1.591f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.rocket.node.top] run data merge entity @s { transformation: [-1.0607f,0f,-1.0607f,0f,0f,1.5f,0f,3.75f,1.0607f,0f,-1.0607f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.rocket.node.rocket] run data merge entity @s { transformation: [-4.5833f,0f,0f,0f,0f,4.5833f,0f,0f,0f,0f,-4.5833f,0f,0f,0f,0f,1f], start_interpolation: -1 }