# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mcdevyt.root] run return 0
execute if entity @s[tag=aj.mcdevyt.animation.floating.playing] run function animated_java:mcdevyt/animations/floating/zzz/on_tick
execute on passengers run rotate @s ~ ~