# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:test rig_hash set value '690b85c6ba996df2425a2553955c83c262bb2714e92aa644a66fb151ca175bfc'
scoreboard objectives add aj.float.frame dummy