# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:minecart ^0 ^1.6875 ^0 {Tags:["aj.global.bone.rocket.child","aj.global.bone.rocket.child.locator","aj.global.bone.rocket.decendant","aj.global.bone.rocket.decendant.locator","aj.global.bone.rocket.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator","aj.new","aj.rocket.bone.rocket.child","aj.rocket.bone.rocket.child.locator","aj.rocket.bone.rocket.decendant","aj.rocket.bone.rocket.decendant.locator","aj.rocket.bone.rocket.tree","aj.rocket.entity","aj.rocket.locator","aj.rocket.locator.locator","aj.rocket.node","aj.rocket.node.locator"]}
execute as @n[ type=minecraft:minecart, tag=aj.rocket.locator.locator, tag=aj.new, distance=..2 ] run function animated_java:rocket/zzz/summon/as_data_entity/as_locator/locator
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_locator set from storage animated_java:gu out
data modify entity @s data.locators.locator.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.pillar] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_pillar set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.thrust] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_thrust set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.pillar1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_pillar1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.pillar2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_pillar2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.pillar3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_pillar3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.top] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_top set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.top1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_top1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.top2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_top2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.top3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_top3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.roof] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_roof set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.window] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_window set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.window3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_window3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.window2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_window2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.window4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_window4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.rocket] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rocket set from storage animated_java:gu out