# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:winningfighter/animations/pause_all
tag @s add aj.winningfighter.animation.winningfighter_floating.playing
scoreboard players set @s aj.winningfighter_floating.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:winningfighter/animations/winningfighter_floating/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only