# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '3eef2017c38a95bfa1306827a1d2b07262fa411146d00ce7f58f64f49ebd4a66'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack