# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rocket.root] run return 0
execute if entity @s[tag=aj.rocket.animation.animation_rocket_idle.playing] run function animated_java:rocket/animations/animation_rocket_idle/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:rocket/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~