# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:winningfighter rig_hash set value '3eef2017c38a95bfa1306827a1d2b07262fa411146d00ce7f58f64f49ebd4a66'
scoreboard objectives add aj.winningfighter_floating.frame dummy